# Generated by Django 4.0.4 on 2022-05-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=11)),
                ('real_estate_agency', models.CharField(max_length=50)),
                ('order_description', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=25)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
